language:
  - python
python:
  - 2.6
  - 2.7
install:
  - pip install 'unittest2'
  - pip install 'flake8'
  - pip install 'pep8-naming'
  - pip install 'flake8-blind-except'
  - pip install 'pycodestyle'
before_script:
  - pwd
  - ls -lah
  - flake8 --help
  - flake8 --config .flake8 pilot.py pilot/
script:
  -  unit2 -v
